---
  - name: "update and update pt packages."
    become: true
    apt:
      update_cache: yes
      upgrade: yes
  
  - name: "Install Nodejs and npm"
    apt:
      name:
        - nodejs
        - npm
      state: present
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Creates working directory
    file:
      path: ~/web
      state: directory
  
  - name: Copy index test page
    template:
      src: "files/index.js"
      dest: "~/web/index.js"
  
  - name: Executing node
    shell: |
      pm2 start ~/web/index.js -f